before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
language: python
python:
- '3.5'
install:
- pip install -e .
- pip install pytest-cov
script:
- py.test --cov acp_paper_analysis
#after_success:
#- bash <(curl -s https://codecov.io/bash)